// Application actions
export const API_CALL_STARTED = 'API_CALL_STARTED';
export const API_CALL_COMPLETED = 'API_CALL_COMPLETED';

// Content actions
export const CONTENT_UPDATED = 'CONTENT_UPDATED';
export const CONTENT_API_CALLED = 'CONTENT_API_CALLED';

//Form actions
export const SKIP_DIRTY = 'SKIP_DIRTY';

//Search Plan actions
export const PLANS_SEARCH_SUCCESS = 'PLANS_SEARCH_SUCCESS';
export const PLAN_ADD_SUCCESS = 'PLAN_ADD_SUCCESS';
export const CLEAR_PLANS = 'CLEAR_PLANS';

//Plan Details actions
export const PLAN_GET_SUCCESS = 'PLAN_GET_SUCCESS';
export const WITHDRAWAL_GET_SUCCESS = 'WITHDRAWAL_GET_SUCCESS';

//My Profile actions
export const GET_MY_PROFILE_SUCCESS = 'GET_MY_PROFILE_SUCCESS';
export const UPDATE_MY_PROFILE_SUCCESS = 'UPDATE_MY_PROFILE_SUCCESS';
export const GET_USER_VALIDATION_STATUS_SUCCESS = 'GET_USER_VALIDATION_STATUS_SUCCESS';
export const UPDATE_UPGRADE_ACCESS_CLICKED_COUNT = 'UPDATE_UPGRADE_ACCESS_CLICKED_COUNT';
//export const UPDATE_MY_PROFILE_FAILURE = 'UPDATE_MY_PROFILE_FAILURE';

export const RESET_FORM_SUCCESS = 'RESET_FORM_SUCCESS';

//Servicing
export const BANK_SEARCH_SUCCESS = 'BANK_SEARCH_SUCCESS';

//Servicing Amend
export const AMEND_PERSONAL_DETAILS_SUCCESS = 'AMEND_PERSONAL_DETAILS_SUCCESS';

//Agency Code
export const AGENCY_CODE_QUERY_SUCCESS = 'AGENCY_CODE_QUERY_SUCCESS';
export const AGENCY_CODE_ADD_SUCCESS = 'AGENCY_CODE_ADD_SUCCESS';
export const DELETE_AGENCY_CODES = 'DELETE_AGENCY_CODES';

//Delegation
export const DELEGATION_QUERY_SUCCESS = 'DELEGATION_QUERY_SUCCESS';
export const DELEGATION_ADD_SUCCESS = 'DELEGATION_ADD_SUCCESS';
export const DELETE_DELEGATIONS = 'DELETE_DELEGATIONS';

//User validation status
export const GET_USER_VALIDATION_SUCCESS = 'GET_USER_VALIDATION_SUCCESS';

//History
export const GET_HISTORY_SUCCESS = 'GET_HISTORY_SUCCESS';
export const GET_HISTORY_DETAILS_SUCCESS = 'GET_HISTORY_DETAILS_SUCCESS';

