const ServicingTypes = {
    // AMEND: 'amend',
    // REGULAR_WITHDRAWAL: 'regular-withdrawal',
    // INCOME_PAYMENT: 'income-payment',
    // DISTRIBUTION: 'distribution',
    // SURRENDER: 'surrender',
    // SWITCH_FUND: 'switch-fund',
    // REDIRECT_CONTRIBUTION: 'redirect-contribution',

    // AMEND
    AMEND_PERSONAL_DETAILS: "AMEND_PERSONAL_DETAILS", 
    AMEND_TRUSTEE_DETAILS: "AMEND_TRUSTEE_DETAILS",
    AMEND_ORGANISATION_DETAILS: "UPDATE_COMPANY_DETAILS",
    AMEND_RETIREMENT_AGE: "AMEND_RETIREMENT_AGE",

    // REGULAR WITHDRAWAL
    ADD_REGULAR_WITHDRAWAL: "ADD_REGULAR_WITHDRAWAL",
    AMEND_REGULAR_WITHDRAWAL: "AMEND_REGULAR_WITHDRAWAL",
    REMOVE_REGULAR_WITHDRAWAL: "REMOVE_REGULAR_WITHDRAWAL",

    // INCOME PAYMENT
    INCOME_PAYMENT: "INCOME_PAYMENTS",
    ADD_INCOME_PAYMENT: "ADD_INCOME_DRAWDOWN_PAYMENT", 
    AMEND_INCOME_PAYMENT_ACCROSS: "AMEND_INCOME_DRAWDOWN_PAYMENT_ACROSS",
    AMEND_INCOME_PAYMENT_SPECIFIC: "AMEND_INCOME_DRAWDOWN_PAYMENT_SPECIFIC", 
    REINVEST_INCOME: "REINVEST_INCOME",
    STOP_INCOME_PAYMENT: "STOP_INCOME_DRAWDOWN_PAYMENT",

    // DISTRIBUTION
    CHANGE_DISTRIBUTION: "CHANGE_DISTRIBUTION",
    AMEND_DISTRIBUTION_PAYMENT: "AMEND_DISTRIBUTION_PAYMENT",
    STOP_DISTRIBUTION: "STOP_DISTRIBUTION",

    // SURRENDER
    SURRENDER: "SURRENDER",
    PARTIAL_SURRENDER_ACROSS_ALL: "PARTIAL_SURRENDER_ACROSS_ALL",
    PARTIAL_SURRENDER_SPECIFIC_FUNDS: "PARTIAL_SURRENDER_SPECIFIC_FUNDS",

    // SWITCH FUND
    SWITCH_FUND: "FUND_SWITCH",
    REBALANCE_FUND: "REBALANCE_FUNDS",
        
    // REDIRECT CONTRIBUTION
    REDIRECT_CONTRIBUTION: "REDIRECT_CONTRIBUTIONS",
    REDIRECT_REGULAR_PAYMENT: "REDIRECT_REGULAR_PAYMENTS",
           
    // OTHER
    TRADE_EQUITIES: "TRADE_EQUITIES",
    TRADE_FUNDS: "TRADE_FUNDS" 
};

export default ServicingTypes;